---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: udagram-jwt
  namespace: classlab-code-dev
spec:
  encryptedData:
    JWT_SECRET: AgAlH2Zv7zQLtqZ2tUS9r6FDpa+qB6MhG5pTEXZsgVI3JXn8BFYrg8oZQRfu914mQ0DzYjXixlTPDCD7jhdSU3jIb+PyXJ0MdjnpVA6wvAp1/Qx0AEUyqmeS0u9/HVE+1fyhxLWieZX0KpNy+j9mjPdf/ytWIcsE09apnjz0mLbrEUp1NOtLAWBYLeBrNIUzDXJN0kTBfjAv97kCikhs0b7o6yFAkdKxeWlVEpiz2MV1dH60X1iiS/UbECsoiFRe2IapTG2iUhQuBTROiLi+GOqfNLfV3IzLMJ0l3rCmpygK2uDmqstqCwau3n5vUKrYrSgIY9Po8uqCaGn6j6Mk7stPCNYobDcF7EcgWC/waCTUW5b6QL1NzDibvTApagJ/1+3r8Zc1CIj9Z1oNQAKE3r0BUX4QceVgfhMwMYEgINHcAwFWFZ2ywBwNX0muLnIkdUlHu+hA0iUySJok8vf/xfDLon+IPiKUtw4J3cTiGkaMcu86gMKhxst1v7bCXnEYf9UqI30OSWcYiFAaDDbcykEn8EGGEAfn8g0NsVclE0AtnLA7FMkKnykn8BDC9JxnpcL/U9OHECkocCUo6K0bjbPXRJnQqGdQ0NqOjynwECALevog9jHHQqXic7p0Xyy+PYn6zh6apjtGZQ6LPA9EGdHq414Aqx9LPpyT2HcuBAXjuBw4W0OBCYGAn+UBFRiwFiTH0xJfrV1n4Xkyo4MYtQ7K3tZ+nPVpJMTSI1NJUVlm4f5xaYZryHc4vMmZKOBF90Z1CFUQex41kv+YPzY4snSb
  template:
    metadata:
      name: udagram-jwt
      namespace: classlab-code-dev
