# Overlay DEV — namespace classlab-code-dev, images :latest (Image Updater = newest-build).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: classlab-code-dev
resources:
  - ../../base
  - jwt-sealedsecret.yaml
images:
  - name: ghcr.io/mateplo/udagram-frontend
    newTag: dev-946e870
    newName: ghcr.io/mateplo/udagram-frontend
  - name: ghcr.io/mateplo/udagram-restapi-user
    newTag: dev-946e870
    newName: ghcr.io/mateplo/udagram-restapi-user
  - name: ghcr.io/mateplo/udagram-restapi-feed
    newTag: dev-946e870
    newName: ghcr.io/mateplo/udagram-restapi-feed
  - name: ghcr.io/mateplo/udagram-restapi-image-filter
    newTag: dev-946e870
    newName: ghcr.io/mateplo/udagram-restapi-image-filter
patches:
  - target: {kind: ConfigMap, name: app-env}
    patch: |
      - op: replace
        path: /data/URL
        value: https://udagram-dev.classlab.lan
  - target: {kind: HTTPRoute, name: udagram}
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: udagram-dev.classlab.lan
