---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: udagram-jwt
  namespace: classlab-code-staging
spec:
  encryptedData:
    JWT_SECRET: AgBGCLOuOMHsYu/hLqJc3kjObN5lyKkTXqFm/sXVVpCNOye2xiM9QV6cG/06DxH8tO9COzn9U6n8sM5dw/7/WE0gq2s1uxUITAoIwnyajrQuqqVZmr7vHMNhPkgn20uoKgRa4APCpO+E5il7OkHi5ZMqiTerrrCun3uslPC+CCiSDmTYsriQTk96nbJZibXmjDHh5bw4ZT8NrRu6VdxC22eplEr+C8KESzr9xIXrUw5gqYvMSSF6QwvqoxSVFaaoeWMGQLLTnlhWlOUu6IVPz3jEXYMSf8edm+6sNEe1B+wjw0XHr60lPAJ8Nxwh+NSQDrH2YrGvry6RTL+yVhoL98TyX9buvhUnd/l648voEV3nY9NA12Jg8TjJuD+/leYNMxj52OmhQRC2qRNGFyFhSoe9KShnw/SuhVLNanRexsYuDtbac7VTVgdOv3u3WAY7Nt1FtQhdUTzY1d7C4GW6uVvw1KFTKdA+eclv+2Lwgehe1eZLuvlOB0Tq3fbt7/gvFfNEQ7Km4VbjoEf4BaLqr7SnipE5oRP4joNNKT+NHYvzunzj8ZQsn3hLJICfDjfltTQF0rH+u80sisWRCN/epJR+tMTRd0WLsGj61UCNwiYGqpWZjxUItBuB4s4XlsTut48QJX5YBzi9O8hbSI3bxMh8QbpPAb5lhpfpQn7ncDBY2e8CZLS0U0o1DBOk6FzPz/ojz47wCtDifu6WAsAquOA3aq5hOh9vO3DZIivc3ZuKfDD3wivGrYqXfm+yA1U71AQwkTWNnXB+aZL59oeVKUvx
  template:
    metadata:
      name: udagram-jwt
      namespace: classlab-code-staging
