# Overlay STAGING — namespace classlab-code-staging, images :latest.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: classlab-code-staging
resources:
  - ../../base
  - jwt-sealedsecret.yaml
images:
  - name: ghcr.io/mateplo/udagram-frontend
    newTag: staging
  - name: ghcr.io/mateplo/udagram-restapi-user
    newTag: staging-b34b993
    newName: ghcr.io/mateplo/udagram-restapi-user
  - name: ghcr.io/mateplo/udagram-restapi-feed
    newTag: staging-b34b993
    newName: ghcr.io/mateplo/udagram-restapi-feed
  - name: ghcr.io/mateplo/udagram-restapi-image-filter
    newTag: staging-b34b993
    newName: ghcr.io/mateplo/udagram-restapi-image-filter
patches:
  - target: {kind: ConfigMap, name: app-env}
    patch: |
      - op: replace
        path: /data/URL
        value: https://udagram-staging.classlab.lan
  - target: {kind: HTTPRoute, name: udagram}
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: udagram-staging.classlab.lan
