---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: udagram-jwt
  namespace: classlab-code-prod
spec:
  encryptedData:
    JWT_SECRET: AgBxW4w6qqOZgVx9X1+uKfxh1YT6TuSLVcJkm4/yFhlB2NVO7rJn6viPzUqAsjFN2jtBrnxRpLUA7NhYqujvFbeNVt7BG28JPAG8nsya+os9q+teJl6Umz/AWNiTU4mpVFU2aKVcN7pathwkWoYMpDs3UcWnARu+NcDbzQRUipItq8ETR0JvVbOnU/MWfwASL+HKRpe+j7WzYLWnt9T6aV9ouR1QOLU35WojFinJ1EZsSon0og57iavyKWFyQTsgsHgoQnKKR+Nnca9B4h8Jb8MbEuJttRdOzPKNFblMZB3T2D9h0/rEQAKRt+nH8ENxyBjOnwUEvAb9IYogNOlW5wiuN8EtUzkIpBA1koaf1nSeUX1yewtclPsAD8pI/NGzBJG45jsZdw9D/1nYHunSq3iBun77QG+zOJSkpjYMlbGt018IoxjEQKTo0AheDJM/UwTBXk9C18dSnCxWZP6cc19P7eXIyAdLUuKQ8uflqSMDXNofv/K188MlFetY48+pXIekHmm/1Z/AE16tXOAqF//WI3HJUt6n8WdzzT/wljkrUBBOYdAk4ArHyy/7dMJMaQsrnx6oRYCfHO5D/tU2xY3WWoCHIkksvpxB/5TjDL2mpYhmS6EkuxJ+ZU7llrsfmwVm7pBtI++qo9ageVH4Q1CaXRhEeFIvdIZJ2wjlXaJeKt0k/ShehSLp4E0kzcIhhH3Ldjx+pZ/aknLR3jRo2K8lMSaz9QcAXDDM3kutjqnhGrt4uFQik91WXzj1IdwmBEBU5131AllBteYRxsZkdcwb
  template:
    metadata:
      name: udagram-jwt
      namespace: classlab-code-prod
